backend/src/main/java/com/gdsc/backend/BackendApplication.java, backend/src/main/java/com/gdsc/backend/entity/BaseTimeEntity.java, backend/src/main/java/com/gdsc/backend/entity/Diary.java, backend/src/main/java/com/gdsc/backend/entity/enums/EmotionType.java, backend/src/main/java/com/gdsc/backend/repository/DiaryRepository.java, backend/src/test/java/com/gdsc/backend/repository/DiaryEntityTest.java
PostgreSQL에 사용되는 다이어리 테이블 생성 및 데이터 저장 기능 테스트를 추가하였습니다.
=> DAS-52 다이어리 스키마 생성

frontend/public/index.html, frontend/src/App.tsx, frontend/src/layouts/Layout/index.tsx, frontend/src/pages/Diary/index.tsx, frontend/tsconfig.json, frontend/webpack.config.ts
- React Router 설정
- main을 Diary페이지로 연결
- Layout 설정
=> DAS-57 다이어리 메인페이지 라우터 설정

frontend/package-lock.json, frontend/package.json, frontend/src/pages/Diary/index.tsx, frontend/webpack.config.ts
- 임시로 만들어진 postman api 주소로 `GET`요청
- 다이어리 컨텐츠 데이터를 가져옴
- `swr`과 `axios`사용
=> DAS-65 다이어리 컨텐츠 데이터 GET 요청

frontend/src/App.tsx, frontend/src/components/atoms/inputs/DiaryInput/index.tsx, frontend/src/components/atoms/inputs/DiaryInput/styles.ts, frontend/src/pages/DiaryPost/index.tsx
`Diary post` 페이지에 사용자가 다이어리 글을 입력할 수 있는 폼 만듦
- `Post` 페이지 라우터 연결
- `DiaryInput` atomic component 적용
- 입력 `form` 만듦
=> DAS-58 사용자 다이어리 글 입력 폼

frontend/src/pages/DiaryPost/index.tsx
=> DAS-68 사용자가 작성한 다이어리 글 POST 요청

frontend/.eslintrc.json, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/pages/Diary/index.tsx, frontend/src/recoil/Diary/diary.ts, frontend/src/recoil/Diary/hooks.ts, frontend/src/recoil/Diary/index.ts, frontend/src/recoil/Diary/types.ts
Diary 상태관리를 위해서 Recoil 설치
- `Diary` atoms 만듦
- `Diary` selectors 만듦
- Diary GET Request 후 `atoms` 상태 업데이트(`selectors`)
- Diary페이지 Diary내용 `atoms`에서 가져오기
=> DAS-56 다이어리 상태 관리를 위한 Recoil 연결하기

backend/build.gradle, backend/src/main/java/com/gdsc/backend/config/SecurityConfig.java
DAS-69 Cros 에러가 발생하는 부분에 맞춰 Cors 정책 설정을 추가하였습니다.
=> DAS-69 Cors 정책 설정

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
```
Error: firebase.json file not found. 
If your firebase.json file is not in the root of your repo, 
edit the entryPoint option of this GitHub action.
```
=> fix: Github Actions EntryPoint Option Error

.github/workflows/firebase-hosting-merge.yml
일전의 `working-directory` setting이 적용되지 않았다(#18)
```
defaults:
run:
working-directory: frontend
```
로 적용 테스트를 하는 pr입니다.
=> fix: Github Actions `working-directory` settings

.github/workflows/firebase-hosting-merge.yml
Github Actions에서 프라이빗한 환경변수를 사용하기 위해서
Secrets을 통해 env 파일을 생성
=> feat: Add actions secret key

frontend/src/pages/Diary/index.tsx, frontend/src/pages/DiaryPost/index.tsx
Github Actions에 설정한 환경변수에 맞게 소스코드 수정
=> fix: Add Env Variable for Github Action

.github/workflows/firebase-hosting-merge.yml
```
echo "export const DASONI_BACKEND_API=$DASONI_BACKEND_API" >> ./src/.env/index.ts
```
위 코드에 대해서 
```
./src/.env/index.ts: No such file or directory
```
에러가 떴다.
폴더구조를 `.env/index.ts`에서 `src/secret/index.ts`로 바꾸고, 파일안에 작성할 코드도 `ts`확장자에서 변수를 사용할 수 있게 변경해줬다
=> fix: error `./src/.env/index.ts` No such file or directory

.github/workflows/firebase-hosting-merge.yml
syntax에러. 리눅스 명령어 마지막에 `;` 추가
```bash
TS1005: ',' expected.
```
=> fix: `echo`명령어 마지막에 `;` 추가

backend/src/main/java/com/gdsc/backend/BackendApplication.java, backend/src/main/java/com/gdsc/backend/controller/DiaryController.java, backend/src/main/java/com/gdsc/backend/entity/Diary.java, backend/src/main/java/com/gdsc/backend/http/response/DiaryResponse.java, backend/src/main/java/com/gdsc/backend/repository/DiaryRepository.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java, backend/src/main/resources/application-prod.yml
add detail search diary method
=> Das 64 search diary

backend/src/main/java/com/gdsc/backend/controller/BoardController.java, backend/src/main/java/com/gdsc/backend/controller/DiaryController.java, backend/src/main/java/com/gdsc/backend/entity/Board.java, backend/src/main/java/com/gdsc/backend/entity/enums/BoardCategory.java, backend/src/main/java/com/gdsc/backend/http/response/BoardListResponse.java, backend/src/main/java/com/gdsc/backend/http/response/BoardResponse.java, backend/src/main/java/com/gdsc/backend/http/response/DiaryResponse.java, backend/src/main/java/com/gdsc/backend/repository/BoardRepository.java, backend/src/main/java/com/gdsc/backend/service/BoardService.java, docker-compose.yml
지원사업 카테고리별로 조회함. docker compose 파일에 pgadmin container 추가함.
=> DAS-40 지원 사업 조회 API 생성

backend/src/main/java/com/gdsc/backend/config/SecurityConfig.java, frontend/src/pages/Login/index.tsx
회원 가입시 사용된 계정이 권한 상승이 안되었던 문제를 해결하였습니다.
=> DAS-81 resolve error creating account

frontend/src/App.tsx, frontend/src/components/molecules/forms/DiaryPostFrom/index.tsx, frontend/src/hooks/useUserActions/index.ts, frontend/src/layouts/SubPageLayout/index.tsx, frontend/src/pages/DiaryPost/index.tsx, frontend/src/pages/DiaryWeeklyList/index.tsx, frontend/src/pages/Login/index.tsx, frontend/src/recoil/Auth/auth.ts, frontend/src/recoil/Auth/hooks.ts, frontend/src/recoil/Auth/index.ts, frontend/src/recoil/Auth/types.ts, frontend/src/recoil/User/index.ts, frontend/src/recoil/User/user.ts, frontend/webpack.config.ts
Recoil을 이용해 프런트에서 유저정보를 가지고 있는다.
유저 토큰의 경우 `Auth` 부분에, 유저 정보의 경우 `User` 부분에 저장했다.
- `atom`으로 `Auth`와 `User`정보 저장
- get selector로 `Auth`와 `User` 정보 읽을 수 있게 함
- `Login` hook function 을 만들어서 atom의 `Auth`에 토큰 저장되게 함
- `Logout` hook function 을 만들어서 atom의 `Auth` 토큰 `Null`로 바꿔줌
=> DAS-78 Access Token 유저정보 가지고 있기

docker-compose.yml
불필요한 Docker 컨테이너가 생성되는 현상을 제거하였습니다.
=> fix: remove unused container

backend/src/main/java/com/gdsc/backend/config/SecurityConfig.java
=> fix: fix cors error

frontend/src/App.tsx, frontend/src/components/atoms/buttons/ClickButton/index.ts, frontend/src/components/atoms/wrapper/Header/index.ts, frontend/src/hooks/useUserActions/index.ts, frontend/src/pages/Signup/index.tsx, frontend/src/pages/Signup/styles.ts, frontend/src/recoil/Auth/auth.ts, frontend/src/recoil/Auth/types.ts, frontend/src/recoil/User/hooks.ts, frontend/src/recoil/User/types.ts, frontend/src/recoil/User/user.ts
사용자가 현재 상태 선택 후 회원가입 진행
- `PATCH` 요청을 통해 유저 정보 업데이트
- `signup` hook function 추가
- `user` atom 값 사용자가 선택한 값으로 변경
=> DAS-83 회원가입

backend/src/main/java/com/gdsc/backend/controller/DiaryController.java, backend/src/main/java/com/gdsc/backend/entity/Diary.java, backend/src/main/java/com/gdsc/backend/http/request/DiaryRequest.java, backend/src/main/java/com/gdsc/backend/http/response/DiaryContentResponse.java, backend/src/main/java/com/gdsc/backend/http/response/DiaryResponse.java, backend/src/main/java/com/gdsc/backend/repository/DiaryRepository.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java
diary를 생성할 수 있는 POST 형식의 메소드를 생성하였습니다.
Type of change
Checklist:
=> DAS-53 Create diary post method

backend/src/main/java/com/gdsc/backend/repository/DiaryRepository.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java
사용자 인증 정보를 통해 다이어리를 삭제할 수 있도록 변경하였습니다.
Type of change
Checklist:
=> DAS-80 feature: add diary delete method

frontend/src/components/atoms/buttons/ToggleSwitchButton/styles.ts, frontend/src/components/atoms/buttons/WriteButton/styles.ts, frontend/src/components/molecules/boxes/DiaryContentBox/styles.ts, frontend/src/components/molecules/boxes/ShadowBox/styles.ts, frontend/src/components/molecules/calendars/DailyCalendar/styles.ts, frontend/src/hooks/useDiaryActions/index.ts, frontend/src/layouts/MainLayout/index.tsx, frontend/src/layouts/MainLayout/styles.ts, frontend/src/layouts/SubPageLayout/index.tsx, frontend/src/pages/Diary/index.tsx, frontend/src/pages/Diary/styles.ts, frontend/src/recoil/Diary/diary.ts, frontend/src/recoil/Diary/hooks.ts, frontend/src/recoil/Diary/types.ts
로그인하고 회원인 사용자만 입력한 다이어리 기록을 볼 수 있도록 함
- `diariesAtom` atom 설정
- `getDiaries` hook function 추가
- 다이어리 GET 요청에 SWR 적용
- 다이어리 수정사항 적용
=> DAS-82 로그인을 한 사용자만 입력한 다이어리 기록 보여주기

frontend/src/components/molecules/forms/DiaryPostFrom/index.tsx, frontend/src/components/molecules/forms/DiaryPostFrom/styles.ts, frontend/src/hooks/useDiaryActions/index.ts
회원인 사용자가 다이어리를 기록할 수 있도록 함
- `postDiary` hook function 추가
- 작성 후 메인페이지로 이동
=> DAS-68 사용자가 작성한 다이어리 글 POST

backend/src/main/java/com/gdsc/backend/controller/DiaryController.java, backend/src/main/java/com/gdsc/backend/entity/Diary.java, backend/src/main/java/com/gdsc/backend/http/request/DiaryRequest.java, backend/src/main/java/com/gdsc/backend/http/response/DiaryContentResponse.java, backend/src/main/java/com/gdsc/backend/repository/DiaryRepository.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java
Diary 정보를 수정하는 메소드를 추가하였습니다.
Type of change
Checklist:
=> DAS-62 Add diary patch method

backend/src/main/java/com/gdsc/backend/controller/DiaryController.java, backend/src/main/java/com/gdsc/backend/entity/Diary.java, backend/src/main/java/com/gdsc/backend/http/request/NaturalLanguageRequest.java, backend/src/main/java/com/gdsc/backend/http/response/DiaryContentResponse.java, backend/src/main/java/com/gdsc/backend/http/response/DocumentSentiment.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java, backend/src/main/java/com/gdsc/backend/service/util/NaturalLanguage.java
Diary 정보 추가 혹은 수정시 작성 내용을 분석하여 감정을 판단하는 기능을 추가하였습니다.
Type of change
Checklist:
=> DAS-90 natural language

backend/src/main/java/com/gdsc/backend/controller/StatisticsController.java, backend/src/main/java/com/gdsc/backend/http/response/CalendarResponse.java, backend/src/main/java/com/gdsc/backend/repository/DiaryRepository.java, backend/src/main/java/com/gdsc/backend/service/StatisticsService.java
월별 캘린더에 표시할 감정 목록을 조회하는 기능을 추가하였습니다.
Type of change
Checklist:
=> DAS-93 get calendar info

backend/src/main/java/com/gdsc/backend/controller/StatisticsController.java, backend/src/main/java/com/gdsc/backend/entity/enums/EmotionType.java, backend/src/main/java/com/gdsc/backend/http/response/ChartResponse.java, backend/src/main/java/com/gdsc/backend/repository/DiaryRepository.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java, backend/src/main/java/com/gdsc/backend/service/StatisticsService.java
한달의 감정 평균값을 조회할 수 있는 메소드를 추가하였습니다.
Type of change
Checklist:
=> DAS-94 get chart data

backend/src/main/java/com/gdsc/backend/service/StatisticsService.java
=> DAS-94 fix: typo correction

backend/src/main/java/com/gdsc/backend/controller/DiaryController.java, backend/src/main/java/com/gdsc/backend/controller/FeedController.java, backend/src/main/java/com/gdsc/backend/entity/Comment.java, backend/src/main/java/com/gdsc/backend/entity/Diary.java, backend/src/main/java/com/gdsc/backend/entity/Feed.java, backend/src/main/java/com/gdsc/backend/entity/FeedLike.java, backend/src/main/java/com/gdsc/backend/http/response/FeedListResponse.java, backend/src/main/java/com/gdsc/backend/http/response/FeedSimpleResponse.java, backend/src/main/java/com/gdsc/backend/repository/FeedRepository.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java, backend/src/main/java/com/gdsc/backend/service/FeedService.java
공유된 피드를 조회할 수 있는 기능을 추가하였습니다.
Type of change
Checklist:
=> DAS-98 share feed

backend/src/main/java/com/gdsc/backend/controller/FeedController.java, backend/src/main/java/com/gdsc/backend/entity/Feed.java, backend/src/main/java/com/gdsc/backend/entity/FeedLike.java, backend/src/main/java/com/gdsc/backend/http/response/FeedResponse.java, backend/src/main/java/com/gdsc/backend/http/response/FeedSimpleResponse.java, backend/src/main/java/com/gdsc/backend/repository/FeedLikeRepository.java, backend/src/main/java/com/gdsc/backend/service/FeedService.java
공유된 피드를 상세 조회할 수 있는 기능을 추가하였습니다.
Type of change
Checklist:
=> DAS-99 search feed detail

frontend/src/components/atoms/buttons/ToggleMenuButton/index.tsx, frontend/src/components/atoms/buttons/ToggleMenuButton/styles.ts, frontend/src/components/molecules/boxes/DiaryContentBox/index.tsx, frontend/src/components/molecules/boxes/DiaryContentBox/styles.ts, frontend/src/hooks/useDiaryActions/index.ts, frontend/src/pages/Diary/index.tsx
사용자가 다이어리를 삭제할 수 있도록 버튼 생성 및 기능 연결하기
- `deletediary` hook action 생성
- toggle menu로 수정, 삭제, 공유 가능한 버튼 생성
- toggle menu의 delete에 다이어리 삭제 기능 연결
=> DAS-92 사용자가 다이어리를 삭제할 수 있도록 버튼과 기능만들기

backend/src/main/java/com/gdsc/backend/controller/DiaryController.java, backend/src/main/java/com/gdsc/backend/http/response/DiaryContentResponse.java, backend/src/main/java/com/gdsc/backend/service/DiaryService.java
일주일 단위 다이어리 조회를 할 수 있는 메소드를 추가하였습니다.
일주일 감정의 평균을 내는 기능을 추가하였습니다.
Type of change
Checklist:
=> DAS-104 일주일 단위 다이어리 조회

frontend/src/components/molecules/boxes/SuppportContentBox/index.tsx, frontend/src/hooks/useSupportActions/index.ts, frontend/src/pages/Support/index.tsx, frontend/src/recoil/Support/index.ts, frontend/src/recoil/Support/support.ts, frontend/src/recoil/Support/types.ts
지원사업 페이지에 들어갈 데이터 GET요청으로 가져오기
- `getSupports` hook 함수 구현
- `supportsAtom` atoms 생성
=> DAS-105 지원사업 데이터GET요청으로 가져오기

frontend/package-lock.json, frontend/package.json, frontend/src/components/organisms/LineChart/index.tsx, frontend/src/hooks/useStatisticsActions/index.ts, frontend/src/pages/Statistics/index.tsx, frontend/src/pages/Statistics/styles.ts, frontend/src/recoil/Statistics/index.ts, frontend/src/recoil/Statistics/statistics.ts, frontend/src/recoil/Statistics/types.ts
`chart.js`와 `react-chartjs-2`라이브러리를 이용해서 라인 그래프를 표시했다. 그리고 `Statistics` 페이지 구조를 만들고 디자인을 적용했다.
- `Statistics` Atoms 생성
- `useStatisticsActions` hook function 생성
- `LineChart` 컴포넌트 생성
- `Statistics` Page 구조 생성 및 디자인 적용
=> DAS-107 chart.js 라이브러리를 사용해 통계 그래프 표시

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/organisms/Header/index.tsx, frontend/src/components/organisms/Map/index.tsx, frontend/src/pages/Center/index.tsx, frontend/src/pages/Center/styles.ts, frontend/src/pages/Map/index.tsx
센터찾기 페이지에 구글맵 API 연동
- `Map` 컴포넌트에 구글맵 API 연결
- Center Page 구성 및 스타일 적용
=> DAS-108 Google Map API 연동해 센터찾기 페이지에 지도 띄우기

frontend/src/components/atoms/buttons/ToggleMenuButton/index.tsx, frontend/src/components/atoms/inputs/CheckBox/styles.ts, frontend/src/components/molecules/boxes/DiaryContentBox/index.tsx, frontend/src/components/molecules/boxes/SuppportContentBox/index.tsx, frontend/src/components/organisms/LineChart/index.tsx, frontend/src/components/organisms/navbars/SlideBar/index.tsx, frontend/src/hooks/useCenterActions/index.ts, frontend/src/hooks/useDiaryActions/index.ts, frontend/src/hooks/useFeedActions/index.ts, frontend/src/hooks/useStatisticsActions/index.ts, frontend/src/pages/Center/index.tsx, frontend/src/pages/Diary/index.tsx, frontend/src/pages/Feed/index.tsx, frontend/src/pages/Signup/index.tsx, frontend/src/pages/Statistics/index.tsx, frontend/src/pages/Support/index.tsx
- Line Chart 라벨, 제목 변경
- 타겟 변경 적용 (`unmarried` -> `pregnant`)
- 월 표시 숫자에서 문자로 변경 (`3` -> `Mar`)
- `CheckBox` 스타일 변경
- `ToggleMenuButton` 리스트 요소를 선택할 수 있게 변경
- 의미에 따른 영어 단어 변경
=> D112 modified design
